version: 1
accounts:
  - name: user1
    coins: ["1000token", "100000000stake"]
  - name: user2
    coins: ["1000token"]
  - name: ping
    coins: ["1000token"]
  - name: user4
    coins: ["1000token"]
  - name: net
    coins: ["1000token"]
  - name: pleum
    coins: ["1000token"]
  - name: top
    coins: ["1000token"]
validator:
  name: user1
  staked: "100000000stake"
